export const tropeCategories = {
  "❤️ Core Romance Tropes": [
    "enemies to lovers",
    "friends to lovers",
    "fake dating",
    "forbidden love",
    "forced proximity",
    "grumpy/sunshine",
    "marriage of convenience",
    "opposites attract",
    "second chance",
    "slow burn",
    "soulmates / fated mates",
    "secret relationship",
    "arranged marriage",
    "only one bed",
  ],
  "🏠 Settings & Contexts": [
    "small town",
    "workplace romance",
    "college romance",
    "sports romance",
    "billionaire romance",
    "regency / historical romance",
    "urban fantasy",
    "time travel",
    "paranormal romance",
    "dystopian",
    "witchy romance",
    "cowboy / western romance",
  ],
  "🪄 Supernatural & Fantasy Elements": [
    "chosen one",
    "destiny / destined lovers",
    "fae / fae court",
    "shifters / werewolves",
    "vampire romance",
    "angel / fallen angel",
    "reincarnation",
    "cursed hero / heroine",
    "prophecy",
    "magic / magical realism",
    "supernatural politics",
  ],
  "💔 Emotional & Character Themes": [
    "tortured hero / heroine",
    "redemption",
    "trauma and healing",
    "grief and healing",
    "emotional healing",
    "coming of age",
    "self-discovery",
    "obsession",
    "caretaker romance",
    "survivor heroine",
  ],
  "👥 Relationship Dynamics": [
    "protective hero",
    "single parent",
    "bodyguard hero",
    "dominant hero / submissive heroine",
    "mentor/student tension",
    "independent heroine",
    "quirky heroine",
    "reluctant heroine",
    "age gap romance",
    "playboy reformed",
  ],
  "🎭 Themes & Motifs": [
    "betrayal",
    "class difference / social divide",
    "family secrets",
    "hidden identity",
    "morally gray hero",
    "rebellion",
    "revenge",
    "sacrifice",
    "tragic love",
    "workplace power dynamics",
    "comedy / rom-com tone",
  ],
  "📖 Story Structures & Styles": [
    "found family",
    "dual timeline",
    "multiple POV",
    "heist / quest element",
    "instant attraction",
    "messy emotions",
    "slow burn pacing",
    "witty banter",
    "suspense",
    "tragic ending",
  ],
  "🏳️‍🌈 LGBTQ+ & Inclusivity Themes": [
    "LGBTQ+ romance",
    "sapphic romance",
    "coming of age (LGBTQ+)",
    "rivals to lovers (LGBTQ+)",
    "fake dating (LGBTQ+)",
    "found family (LGBTQ+)",
    "coming out arc",
  ],
  "🏞️ Mystery / Adventure Subgenres": [
    "romantic suspense",
    "crime-solving couple",
    "undercover hero",
    "psychic heroine",
    "hacker hero",
    "magical quest",
  ],
  "💎 Unique or Niche Concepts": [
    "rockstar romance",
    "reality TV setting",
    "culinary / foodie romance",
    "bartender romance",
    "STEM romance",
    "wedding planner setting",
    "travel romance",
    "afterlife romance",
  ],
};
